use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};
use tauri::Manager;

const MAX_SYNC_BYTES: u64 = 256 * 1024;
const PREVIEW_CHARS: usize = 4_000;
const CODETAS_MARKER: &str = "<!-- Generated by CODETAS Hermes sync -->\n";

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum HermesSyncKind {
    Context,
    Soul,
    ProfileYaml,
    Memory,
    User,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum HermesSyncScope {
    Project,
    Default,
    Profile,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum HermesSyncDirection {
    Import,
    Export,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum HermesSyncPolicy {
    Overwrite,
    Append,
    Skip,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum HermesSyncItemStatus {
    Create,
    Overwrite,
    Append,
    Unchanged,
    MissingSource,
    Skip,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HermesSyncInventory {
    pub installed: bool,
    pub hermes_home: Option<String>,
    pub codetas_store: String,
    pub project_path: Option<String>,
    pub documents: Vec<InventoryDocument>,
    pub warnings: Vec<String>,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InventoryDocument {
    pub id: String,
    pub kind: HermesSyncKind,
    pub scope: HermesSyncScope,
    pub profile_name: Option<String>,
    pub label: String,
    pub source_path: String,
    pub target_path: String,
    pub source_exists: bool,
    pub target_exists: bool,
    pub source_bytes: u64,
    pub target_bytes: u64,
    pub source_preview: String,
    pub target_preview: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HermesSyncSelection {
    pub id: String,
    pub policy: HermesSyncPolicy,
    pub selected: bool,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HermesSyncPreviewRequest {
    pub direction: HermesSyncDirection,
    pub project_path: Option<String>,
    pub items: Vec<HermesSyncSelection>,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HermesSyncPreviewItem {
    pub id: String,
    pub kind: HermesSyncKind,
    pub scope: HermesSyncScope,
    pub profile_name: Option<String>,
    pub label: String,
    pub direction: HermesSyncDirection,
    pub policy: HermesSyncPolicy,
    pub status: HermesSyncItemStatus,
    pub source_path: String,
    pub target_path: String,
    pub source_content: String,
    pub target_content: String,
    pub proposed_content: String,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HermesSyncPreview {
    pub direction: HermesSyncDirection,
    pub items: Vec<HermesSyncPreviewItem>,
    pub warnings: Vec<String>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HermesSyncApplyItem {
    pub id: String,
    pub policy: HermesSyncPolicy,
    pub content: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HermesSyncApplyRequest {
    pub direction: HermesSyncDirection,
    pub project_path: Option<String>,
    pub items: Vec<HermesSyncApplyItem>,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HermesSyncApplyReport {
    pub written: Vec<String>,
    pub skipped: Vec<String>,
    pub backups: Vec<String>,
}

struct Candidate {
    id: String,
    kind: HermesSyncKind,
    scope: HermesSyncScope,
    profile_name: Option<String>,
    label: String,
    hermes_path: PathBuf,
    store_path: PathBuf,
}

fn hermes_home() -> Option<PathBuf> {
    dirs::home_dir().map(|home| home.join(".hermes"))
}

fn hermes_installed(home: &Path) -> bool {
    home.is_dir()
        && (home.join("hermes-agent").is_dir()
            || home.join("profiles").is_dir()
            || home.join("SOUL.md").is_file()
            || home.join("hermes-setup").is_file())
}

fn store_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    app.path()
        .app_data_dir()
        .map(|directory| directory.join("hermes-sync"))
        .map_err(|error| format!("CODETAS同期フォルダを特定できません: {error}"))
}

fn project_context_file(root: &Path) -> PathBuf {
    for name in [".hermes.md", "HERMES.md"] {
        let candidate = root.join(name);
        if is_regular_file(&candidate) {
            return candidate;
        }
    }
    root.join("HERMES.md")
}

fn is_regular_file(path: &Path) -> bool {
    fs::symlink_metadata(path)
        .ok()
        .is_some_and(|meta| meta.is_file() && !meta.file_type().is_symlink())
}

fn file_len(path: &Path) -> u64 {
    fs::metadata(path).map(|meta| meta.len()).unwrap_or(0)
}

fn read_limited(path: &Path) -> Result<String, String> {
    if !path.exists() {
        return Ok(String::new());
    }
    if !is_regular_file(path) {
        return Err(format!("{} は通常ファイルではありません", path.display()));
    }
    let bytes = fs::read(path).map_err(|error| format!("{} を読めません: {error}", path.display()))?;
    if bytes.len() as u64 > MAX_SYNC_BYTES {
        return Err(format!(
            "{} が大きすぎます（最大 {} バイト）",
            path.display(),
            MAX_SYNC_BYTES
        ));
    }
    String::from_utf8(bytes).map_err(|_| format!("{} は UTF-8 ではありません", path.display()))
}

fn preview_text(value: &str) -> String {
    let mut chars = value.chars();
    let preview: String = chars.by_ref().take(PREVIEW_CHARS).collect();
    if chars.next().is_some() {
        format!("{preview}\n…")
    } else {
        preview
    }
}

fn sanitize_profile_name(name: &str) -> bool {
    !name.is_empty()
        && name != "."
        && name != ".."
        && !name.contains('/')
        && !name.contains('\\')
        && name
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '.'))
}

fn candidates(store: &Path, project_path: Option<&Path>) -> Result<Vec<Candidate>, String> {
    let Some(home) = hermes_home() else {
        return Ok(Vec::new());
    };
    let mut items = Vec::new();
    if let Some(project) = project_path {
        let hermes = project_context_file(project);
        items.push(Candidate {
            id: "project:context".into(),
            kind: HermesSyncKind::Context,
            scope: HermesSyncScope::Project,
            profile_name: None,
            label: "プロジェクト HERMES.md".into(),
            hermes_path: hermes,
            store_path: store.join("project").join("HERMES.md"),
        });
    }
    items.extend([
        Candidate {
            id: "default:soul".into(),
            kind: HermesSyncKind::Soul,
            scope: HermesSyncScope::Default,
            profile_name: None,
            label: "既定 SOUL.md".into(),
            hermes_path: home.join("SOUL.md"),
            store_path: store.join("default").join("SOUL.md"),
        },
        Candidate {
            id: "default:profileYaml".into(),
            kind: HermesSyncKind::ProfileYaml,
            scope: HermesSyncScope::Default,
            profile_name: None,
            label: "既定 profile.yaml".into(),
            hermes_path: home.join("profile.yaml"),
            store_path: store.join("default").join("profile.yaml"),
        },
        Candidate {
            id: "default:memory".into(),
            kind: HermesSyncKind::Memory,
            scope: HermesSyncScope::Default,
            profile_name: None,
            label: "既定 MEMORY.md".into(),
            hermes_path: home.join("memories").join("MEMORY.md"),
            store_path: store.join("default").join("MEMORY.md"),
        },
        Candidate {
            id: "default:user".into(),
            kind: HermesSyncKind::User,
            scope: HermesSyncScope::Default,
            profile_name: None,
            label: "既定 USER.md".into(),
            hermes_path: home.join("memories").join("USER.md"),
            store_path: store.join("default").join("USER.md"),
        },
    ]);
    if let Ok(entries) = fs::read_dir(home.join("profiles")) {
        let mut names = entries
            .flatten()
            .filter(|entry| entry.path().is_dir())
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .filter(|name| sanitize_profile_name(name))
            .collect::<Vec<_>>();
        names.sort();
        for name in names {
            let root = home.join("profiles").join(&name);
            items.push(Candidate {
                id: format!("profile:{name}:soul"),
                kind: HermesSyncKind::Soul,
                scope: HermesSyncScope::Profile,
                profile_name: Some(name.clone()),
                label: format!("{name} SOUL.md"),
                hermes_path: root.join("SOUL.md"),
                store_path: store.join("profiles").join(&name).join("SOUL.md"),
            });
            items.push(Candidate {
                id: format!("profile:{name}:profileYaml"),
                kind: HermesSyncKind::ProfileYaml,
                scope: HermesSyncScope::Profile,
                profile_name: Some(name.clone()),
                label: format!("{name} profile.yaml"),
                hermes_path: root.join("profile.yaml"),
                store_path: store.join("profiles").join(&name).join("profile.yaml"),
            });
            items.push(Candidate {
                id: format!("profile:{name}:memory"),
                kind: HermesSyncKind::Memory,
                scope: HermesSyncScope::Profile,
                profile_name: Some(name.clone()),
                label: format!("{name} MEMORY.md"),
                hermes_path: root.join("memories").join("MEMORY.md"),
                store_path: store.join("profiles").join(&name).join("MEMORY.md"),
            });
            items.push(Candidate {
                id: format!("profile:{name}:user"),
                kind: HermesSyncKind::User,
                scope: HermesSyncScope::Profile,
                profile_name: Some(name.clone()),
                label: format!("{name} USER.md"),
                hermes_path: root.join("memories").join("USER.md"),
                store_path: store.join("profiles").join(&name).join("USER.md"),
            });
        }
    }
    Ok(items)
}

fn paths_for_direction(item: &Candidate, direction: HermesSyncDirection) -> (&Path, &Path) {
    match direction {
        HermesSyncDirection::Import => (&item.hermes_path, &item.store_path),
        HermesSyncDirection::Export => (&item.store_path, &item.hermes_path),
    }
}

fn inventory_document(item: &Candidate) -> InventoryDocument {
    let source_exists = is_regular_file(&item.hermes_path);
    let target_exists = is_regular_file(&item.store_path);
    let source_content = if source_exists {
        read_limited(&item.hermes_path).unwrap_or_default()
    } else {
        String::new()
    };
    let target_content = if target_exists {
        read_limited(&item.store_path).unwrap_or_default()
    } else {
        String::new()
    };
    InventoryDocument {
        id: item.id.clone(),
        kind: item.kind,
        scope: item.scope,
        profile_name: item.profile_name.clone(),
        label: item.label.clone(),
        source_path: item.hermes_path.to_string_lossy().into_owned(),
        target_path: item.store_path.to_string_lossy().into_owned(),
        source_exists,
        target_exists,
        source_bytes: if source_exists {
            file_len(&item.hermes_path)
        } else {
            0
        },
        target_bytes: if target_exists {
            file_len(&item.store_path)
        } else {
            0
        },
        source_preview: preview_text(&source_content),
        target_preview: preview_text(&target_content),
    }
}

fn append_content(existing: &str, incoming: &str) -> String {
    let incoming = incoming.trim_end();
    if incoming.is_empty() {
        return existing.to_string();
    }
    if existing.trim().is_empty() {
        return format!("{incoming}\n");
    }
    if existing.contains(incoming) {
        return existing.to_string();
    }
    let separator = if existing.ends_with('\n') { "" } else { "\n" };
    format!("{existing}{separator}\n§\n{incoming}\n")
}

fn proposed(policy: HermesSyncPolicy, source: &str, target: &str) -> (HermesSyncItemStatus, String) {
    match policy {
        HermesSyncPolicy::Skip => (HermesSyncItemStatus::Skip, target.to_string()),
        HermesSyncPolicy::Overwrite => {
            if source == target && !source.is_empty() {
                (HermesSyncItemStatus::Unchanged, target.to_string())
            } else if target.is_empty() {
                (HermesSyncItemStatus::Create, source.to_string())
            } else {
                (HermesSyncItemStatus::Overwrite, source.to_string())
            }
        }
        HermesSyncPolicy::Append => {
            let next = append_content(target, source);
            if next == target {
                (HermesSyncItemStatus::Unchanged, target.to_string())
            } else if target.is_empty() {
                (HermesSyncItemStatus::Create, next)
            } else {
                (HermesSyncItemStatus::Append, next)
            }
        }
    }
}

fn resolve_project(path: Option<&str>) -> Result<Option<PathBuf>, String> {
    let Some(path) = path.filter(|value| !value.trim().is_empty()) else {
        return Ok(None);
    };
    let root = fs::canonicalize(path).map_err(|error| format!("プロジェクトを開けません: {error}"))?;
    if !root.is_dir() {
        return Err("選択したパスはフォルダではありません。".into());
    }
    Ok(Some(root))
}

fn backup_existing(path: &Path) -> Result<Option<PathBuf>, String> {
    if !is_regular_file(path) {
        return Ok(None);
    }
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0);
    let backup = path.with_extension(format!(
        "{}.bak-{stamp}",
        path.extension()
            .and_then(|value| value.to_str())
            .unwrap_or("md")
    ));
    fs::copy(path, &backup).map_err(|error| format!("バックアップを作れません: {error}"))?;
    Ok(Some(backup))
}

fn atomic_write_text(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| format!("フォルダを作れません: {error}"))?;
    }
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or(0);
    let temp = path.with_extension(format!("tmp-{stamp}"));
    fs::write(&temp, content).map_err(|error| format!("書き込めません: {error}"))?;
    if let Err(error) = fs::rename(&temp, path) {
        let _ = fs::remove_file(&temp);
        return Err(format!("保存できません: {error}"));
    }
    Ok(())
}

fn find_candidate<'a>(items: &'a [Candidate], id: &str) -> Result<&'a Candidate, String> {
    items
        .iter()
        .find(|item| item.id == id)
        .ok_or_else(|| format!("未知の同期項目です: {id}"))
}

#[tauri::command]
pub fn scan_hermes_sync(
    app: tauri::AppHandle,
    project_path: Option<String>,
) -> Result<HermesSyncInventory, String> {
    let store = store_dir(&app)?;
    let project = resolve_project(project_path.as_deref())?;
    let home = hermes_home();
    let installed = home.as_ref().is_some_and(|path| hermes_installed(path));
    let mut warnings = Vec::new();
    if !installed {
        warnings.push("Hermes Agent のインストール（~/.hermes）が見つかりません。".into());
    }
    let documents = if installed {
        candidates(&store, project.as_deref())?
            .iter()
            .map(inventory_document)
            .collect()
    } else {
        Vec::new()
    };
    Ok(HermesSyncInventory {
        installed,
        hermes_home: home.map(|path| path.to_string_lossy().into_owned()),
        codetas_store: store.to_string_lossy().into_owned(),
        project_path: project.map(|path| path.to_string_lossy().into_owned()),
        documents,
        warnings,
    })
}

#[tauri::command]
pub fn preview_hermes_sync(
    app: tauri::AppHandle,
    request: HermesSyncPreviewRequest,
) -> Result<HermesSyncPreview, String> {
    let store = store_dir(&app)?;
    let project = resolve_project(request.project_path.as_deref())?;
    let catalog = candidates(&store, project.as_deref())?;
    let mut items = Vec::new();
    let mut warnings = Vec::new();
    for selection in request.items {
        if !selection.selected {
            continue;
        }
        let item = find_candidate(&catalog, &selection.id)?;
        let (source, target) = paths_for_direction(item, request.direction);
        let source_exists = is_regular_file(source);
        let target_exists = is_regular_file(target);
        let source_content = if source_exists {
            read_limited(source)?
        } else {
            String::new()
        };
        let target_content = if target_exists {
            read_limited(target)?
        } else {
            String::new()
        };
        let (mut status, proposed_content) =
            proposed(selection.policy, &source_content, &target_content);
        if !source_exists {
            status = HermesSyncItemStatus::MissingSource;
            warnings.push(format!("{} のコピー元がありません", item.label));
        }
        items.push(HermesSyncPreviewItem {
            id: item.id.clone(),
            kind: item.kind,
            scope: item.scope,
            profile_name: item.profile_name.clone(),
            label: item.label.clone(),
            direction: request.direction,
            policy: selection.policy,
            status,
            source_path: source.to_string_lossy().into_owned(),
            target_path: target.to_string_lossy().into_owned(),
            source_content,
            target_content,
            proposed_content,
        });
    }
    Ok(HermesSyncPreview {
        direction: request.direction,
        items,
        warnings,
    })
}

#[tauri::command]
pub fn apply_hermes_sync(
    app: tauri::AppHandle,
    request: HermesSyncApplyRequest,
) -> Result<HermesSyncApplyReport, String> {
    let store = store_dir(&app)?;
    let project = resolve_project(request.project_path.as_deref())?;
    let catalog = candidates(&store, project.as_deref())?;
    let mut written = Vec::new();
    let mut skipped = Vec::new();
    let mut backups = Vec::new();
    for item in request.items {
        if item.policy == HermesSyncPolicy::Skip {
            skipped.push(format!("{}: スキップ", item.id));
            continue;
        }
        if item.content.len() as u64 > MAX_SYNC_BYTES {
            return Err(format!("{} の内容が大きすぎます", item.id));
        }
        let candidate = find_candidate(&catalog, &item.id)?;
        let (_source, target) = paths_for_direction(candidate, request.direction);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent).map_err(|error| format!("フォルダを作れません: {error}"))?;
        }
        if let Some(backup) = backup_existing(target)? {
            backups.push(backup.to_string_lossy().into_owned());
        }
        let mut content = item.content;
        if request.direction == HermesSyncDirection::Import
            && candidate.kind != HermesSyncKind::ProfileYaml
            && !content.contains("Generated by CODETAS")
        {
            content = format!("{CODETAS_MARKER}{content}");
        }
        atomic_write_text(target, &content)?;
        written.push(target.to_string_lossy().into_owned());
    }
    Ok(HermesSyncApplyReport {
        written,
        skipped,
        backups,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn append_inserts_separator_once() {
        let next = append_content("alpha\n", "beta");
        assert_eq!(next, "alpha\n\n§\nbeta\n");
        assert_eq!(append_content(&next, "beta"), next);
    }

    #[test]
    fn overwrite_detects_unchanged() {
        let (status, value) = proposed(HermesSyncPolicy::Overwrite, "same", "same");
        assert_eq!(status, HermesSyncItemStatus::Unchanged);
        assert_eq!(value, "same");
    }
}
